const items = [
    // Leaves
    { price : "10rs" ,title: "Amaranthus" },
    { price : "10rs" ,title: "Beet Root"},
    { price : "10rs" ,title: "Chukka- sorrel Leaves" },
    { price : "10rs" ,title: "Colocasia Leaves" },
    { price : "10rs" ,title: "Coriander"},
    { price : "10rs" ,title: "Curry Leaves" },
    { price : "10rs" ,title: "Dill" },
    { price : "10rs" ,title: "Fenugreek Leaves"},
    { price : "10rs" ,title: "Green Amaranth" },
    { price : "10rs" ,title: "Spinach" },
    { price : "10rs" ,title: "Spring Onion"},
    { price : "10rs" ,title: "Sufflower" },
  // Wild-Antic
    { price : "10rs" ,title: "Apple Gourd"},
    { price : "10rs" ,title: "Ashgourd" },
    { price : "10rs" ,title: "Chilli" },
    { price : "10rs" ,title: " Colocasia Roots" },
    { price : "10rs" ,title: "Cucumber Madras" },
    { price : "10rs" ,title: "Kohlrabi" },
    { price : "10rs" ,title: "Onion White-Pandhara Kanda" },
    { price : "10rs" ,title: "Pointed Gourd" },
    { price : "10rs" ,title: "Pumpkin" },
    { price : "10rs" ,title: "Raw Jackfruit" },
    { price : "10rs" ,title: "Raw Papaya" },
    { price : "10rs" ,title: "Sambhar Kanda" },
    { price : "10rs" ,title: "Snake Gourd"  },
    { price : "10rs" ,title: "Spiny Gourd" },
    { price : "10rs" ,title: "Sweet Potato" },
    { price : "10rs" ,title: "Water Chestnuts" },
    { price : "10rs" ,title: "Yam" },
  // Exotic
    { price : "10rs" ,title: "Asparagus" },
    { price : "10rs" ,title: "Avocado" },
    { price : "10rs" ,title: "Baby Corn" },
    { price : "10rs" ,title: "Baby Potato" },
    { price : "10rs" ,title: "Basil" },
    { price : "10rs" ,title: "Broccoli" },
    { price : "10rs" ,title: "Celery" },
    { price : "10rs" ,title: "Cherry Tomato" },
    { price : "10rs" ,title: "chinese Cabbage" },
    { price : "10rs" ,title: "Coccinia" },
    { price : "10rs" ,title: "Green Zucchini" },
    { price : "10rs" ,title: "Iceberg Lettuce" },
    { price : "10rs" ,title: "Parsley" },
    { price : "10rs" ,title: "Red Cabbage" },
    { price : "10rs" ,title: "Red Capsicum" },
    { price : "10rs" ,title: "Romaine Lettuce" },
    { price : "10rs" ,title: "Yellow Capsicum" },
    { price : "10rs" ,title: "Yellow Zucchini" },
    { price : "10rs" ,title: "Mushroom" },
    { price : "10rs" ,title: "Sweet Corn" },
    { price : "10rs" ,title: "Sweet Corn Grains" },
  // Special stall
    { price : "10rs" ,title: "Cabbage" },
    { price : "10rs" ,title: "Cauliflower" },
    { price : "10rs" ,title: "Onion" },
    { price : "10rs" ,title: "Potato (Agra)" },
    { price : "10rs" ,title: "Potato (Indore)" },
    { price : "10rs" ,title: "Potato (Talegav)" },
    // Fruit Vegetables
    { price : "10rs" ,title: "Apple Gourd" },
    { price : "10rs" ,title: "Beans Double" },
    { price : "10rs" ,title: "Bitter Gourd" },
    { price : "10rs" ,title: "Brinjal Big" },
    { price : "10rs" ,title: "Brinjal Green" },
    { price : "10rs" ,title: "Brinjal Long Green" },
    { price : "10rs" ,title: "Brinjal Purple" },
    { price : "10rs" ,title: "Carrot" },
    { price : "10rs" ,title: "Cauliflower" },
    { price : "10rs" ,title: "Chavali Beans" },
    { price : "10rs" ,title: "Chickpeas - Chana sprouts" },
    { price : "10rs" ,title: "chilli - Bhavgagari Mirchi" },
    { price : "10rs" ,title: "Chilli Green" },
    { price : "10rs" ,title: "chilli Simple" },
    { price : "10rs" ,title: "Cluster Beans" },
    { price : "10rs" ,title: "Coccinia" },
    { price : "10rs" ,title: "Coconut" },
    { price : "10rs" ,title: "Colocasia Roots" },
    { price : "10rs" ,title: "Coriander" },
    { price : "10rs" ,title: "Cucumber" },
    { price : "10rs" ,title: "Cucumder Madras" },
    { price : "10rs" ,title: "Cucumber Madras- Sambar Kakadi" },
    { price : "10rs" ,title: "Cucumber Polyhouse- English Kakadi" },
    { price : "10rs" ,title: "Curry Leaves" },
    { price : "10rs" ,title: "Drum Sticks" },
    { price : "10rs" ,title: "Elaichi Banana" },
    { price : "10rs" ,title: "Field Beans" },
    { price : "10rs" ,title: "Fresh Peeled Green Peas" },
    { price : "10rs" ,title: "Garlic" },
    { price : "10rs" ,title: "Ginger" },
    { price : "10rs" ,title: "Green Capsicum" },
    { price : "10rs" ,title: "Green Mango" },
    { price : "10rs" ,title: "Green Peas" },
    { price : "10rs" ,title: "Groundnut Pods" },
    { price : "10rs" ,title: "Tamarind" },
    { price : "10rs" ,title: "Lady Finger" },
    { price : "10rs" ,title: "Lemon" },
    { price : "10rs" ,title: "Lemon Grass" },
    { price : "10rs" ,title: "Mint" },
    { price : "10rs" ,title: "Onion" },
    { price : "10rs" ,title: "Onion Sambhar" },
    { price : "10rs" ,title: "Lima Beans" },
    { price : "10rs" ,title: "Peeled Garlic" },
    { price : "10rs" ,title: "Potato" },
    { price : "10rs" ,title: "Radish" },
    { price : "10rs" ,title: "Ridgegourd" },
    { price : "10rs" ,title: "Sponge Gourd" },
    { price : "10rs" ,title: "Spring Onion" },
    { price : "10rs" ,title: "Tomato" },
    { price : "10rs" ,title: "Wal" },
    { price : "10rs" ,title: "Wal Broad" },
    { price : "10rs" ,title: "Wal surati" },
    { price : "10rs" ,title: "Water Chestnuts" },
    // Fruit Export
    { price : "10rs" ,title: "Apple Fuji" },
    { price : "10rs" ,title: "Apple Green" },
    { price : "10rs" ,title: "Apple Kinnaur" },
    { price : "10rs" ,title: "Apple Red Delicious" },
    { price : "10rs" ,title: "Apple Shimla Big" },
    { price : "10rs" ,title: "Kiwi" },
    { price : "10rs" ,title: "Litchi" },
    { price : "10rs" ,title: "Strawberry" },
    // Fruit Summer
    { price : "10rs" ,title: "Grapes Black" },
    { price : "10rs" ,title: "Grapes Green" },
    { price : "10rs" ,title: "Jambhul" },
    { price : "10rs" ,title: "Mango Badami (For Juice)" },
    { price : "10rs" ,title: "Mango Devgad Hapus" },
    { price : "10rs" ,title: "Mango Keshar" },
    { price : "10rs" ,title: "Mango Lalbag" },
    { price : "10rs" ,title: "Mango Payri" },
    { price : "10rs" ,title: "Mango Ratnagiri Hapus" },
    { price : "10rs" ,title: "Mango Totapuri" },
    { price : "10rs" ,title: "Muskmelon" },
    { price : "10rs" ,title: "Watermelon Kiran" },
    { price : "10rs" ,title: "Watermelon Regular" },
    // Fruit
    { price : "10rs" ,title: "Amla" },
    { price : "10rs" ,title: "Apple Gourd" },
    { price : "10rs" ,title: "Ashgourd" },
    { price : "10rs" ,title: "Banana" },
    { price : "10rs" ,title: "Beet Root" },
    { price : "10rs" ,title: "Custard-apple" },
    { price : "10rs" ,title: "Elaichi Banana" },
    { price : "10rs" ,title: "Figs" },
    { price : "10rs" ,title: "Guava" },
    { price : "10rs" ,title: "Jackfruit Peeled" },
    { price : "10rs" ,title: "Jujube - Ber" },
    { price : "10rs" ,title: "Lemon" },
    { price : "10rs" ,title: "Orange Small" },
    { price : "10rs" ,title: "Orange Kinnow" },
    { price : "10rs" ,title: "Papaya" },
    { price : "10rs" ,title: "Pear Imported" },
    { price : "10rs" ,title: "Pomogranate" },
    { price : "10rs" ,title: "Raw Banana" },
    { price : "10rs" ,title: "Sapodilla" },
    { price : "10rs" ,title: "Sugarcane" },
    { price : "10rs" ,title: "Sweet Lime" },
    { price : "10rs" ,title: "Tender" },
  ];


  export default items;